baseURL = "https://blog.lettre.at/"
languageCode = "en-us"
title = "Lettre"
theme = ["lettre", "journal"]

[params]
AuthorName = "amousset"
GithubUsername = "lettre"
twitterusername = "lettre_at"
Tagline = "A mailer library for Rust"
mainSections = [ "post" ]
homepage = "https://lettre.at"
