baseURL = "https://lettre.at/"
languageCode = "en-us"
title = "Lettre"
theme = ["lettre", "journal"]

[author]
name = "Alexis Mousset"

[params]
description = "News about the lettre email library"
Tagline = "A mailer library for Rust"
