baseURL = "https://blog.lettre.at/"
languageCode = "en-us"
title = "lettre"
theme = ["lettre", "journal"]

[author]
name = "Alexis Mousset"

[params]
description = "News about the lettre email library"
Tagline = "a mailer library for Rust"
